steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','gcr.io/$PROJECT_ID/expense-app:latest','.']
- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/expense-app:latest']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - expense-app
    - --image=gcr.io/$PROJECT_ID/expense-app:latest
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars=BQ_PROJECT=$PROJECT_ID,BQ_DATASET=expense_ds,BQ_TABLE=transactions
