steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/deepanexpense/expense-app:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/deepanexpense/expense-app:latest']

# This is the required fix for your error:
options:
  logging: CLOUD_LOGGING_ONLY
